### ISSUE TITLE
3.1 checklist

### ISSUE THREAD

**Issue by iliabylich** [lib-ruby-parser/lib-ruby-parser#29]
- [x] ruby/ruby@9b187fec58 Add `rb_parser_set_pos` function
- [x] ruby/ruby@aa7c4c37d7 Fix arg_forward without parentheses [Bug #18267]
- [x] ruby/ruby@3a6b79d0c0 Revert "Rename `in_kwarg` as `in_argdef` as unrelated to keywords"
- [x] ruby/ruby@637c3cfc5d Turn SET_LEX_STATE macro into an inline function call
- [x] ruby/ruby@a3934cd1e5 Fix indent [ci skip]
- [x] ruby/ruby@54f0e63a8c Remove `NODE_DASGN_CURR` [Feature #18406]
- [x] ruby/ruby@ec7f14d9fa Add `nd_type_p` macro
- [x] ruby/ruby@c14f230b26 Assign temporary ID to anonymous ID [Bug #18250]
- [x] ruby/ruby@feda058531 Refactor hacky ID tables to struct rb_ast_id_table_t
- [x] ruby/ruby@4adb012926 Anonymous block forwarding allows a method to forward a passed block to another method without having to provide a name for the block parameter.
- [x] ruby/ruby@415671a282 parse.y: Fix memory leak at parse error
- [x] ruby/ruby@aeae6e2842 [Feature #18290] Remove all usages of rb_gc_force_recycle
- [x] ruby/ruby@13a9597c7c Argument forwarding definition without parentheses [Bug #18267]
- [x] ruby/ruby@b7f7117bdc Rename `in_kwarg` as `in_argdef` as unrelated to keywords
- [x] ruby/ruby@1b59ad57ae Reduce parser stack usage at pattern matching
- [x] ruby/ruby@e1ecda297e Make new object for negated float as `Float` is always frozen now
- [x] ruby/ruby@09fa773e04 ast.c: Use kept script_lines data instead of re-opening the source file (#5019)
- [x] ruby/ruby@c7550537f1 `RubyVM.keep_script_lines`
- [x] ruby/ruby@fac2c0f73c Fix evaluation order of hash values for duplicate keys
- [x] ruby/ruby@8057129da6 Remove duplicate value checks on `mrhs` which always has the value
- [x] ruby/ruby@a15996c752 Split parser_yyerror0 from parser_yyerror
- [x] ruby/ruby@1f544d6715 Show the last line at unexpected end-of-input error
- [x] ruby/ruby@126122bb6c Replace inaccurate error messages
- [x] ruby/ruby@28392d3045 The same warning for static symbol literal
- [x] ruby/ruby@da139317a5 Fix the warning message for dynamic symbol literal in condition
- [x] ruby/ruby@fa05697e48 Use `%printer` directive for Bison 3.8
- [x] ruby/ruby@7686776c05 Hash values should be omitted in Ripper results
- [x] ruby/ruby@c60dbcd1c5 Allow value omission in Hash literals - done in 11cd261
- [x] ruby/ruby@bdd6d8746f Replace RBOOL macro
- [x] ruby/ruby@c38c2d8ee2 Moved exported symbols in internal/util.h to ruby/util.h
- [x] ruby/ruby@cad83fa3c4 ast.c: Rename "save_script_lines" to "keep_script_lines"
- [x] ruby/ruby@ecb6d6a4ef Allow omission of parentheses in one line pattern matching [Feature #16182] - done in 4f66146
- [x] ruby/ruby@2aa6826e81 Extract the wrapped value when yydebug [Bug #18075]
- [x] ruby/ruby@b940a45357 Fix interpolated heredoc
- [x] ruby/ruby@eed5e8f796 One-line pattern matching is no longer experimental
- [x] ruby/ruby@fa87f72e1e Add pattern matching pin support for instance/class/global variables - done in 4c5fc10
- [x] ruby/ruby@fb01411ae8 node.h: Reduce struct size to fit with Ruby object size (five VALUEs)
- [x] ruby/ruby@acae5f363d ast.rb: RubyVM::AST.parse and .of accepts `save_script_lines: true`
- [x] ruby/ruby@e4f891ce8d Adjust styles [ci skip]
- [x] ruby/ruby@70313ec01a parse.y: Fix the location of a target constant of OP_CDECL
- [x] ruby/ruby@9f3888d6a3 Warn more duplicate literal hash keys - done in 6452c1d
- [x] ruby/ruby@37eb5e7439 Warn more duplicate literal hash keys - done in 6452c1d
- [x] ruby/ruby@50a534a152 ripper: wrap endless method in bodystmt [Bug #17869]
- [x] ruby/ruby@110f242ef9 Also `\U` after control/meta is invalid [Bug #17861] - done in 67f4a11
- [x] ruby/ruby@11ae581a4a Fix handling of control/meta escapes in literal regexps - done in 39800e1
- [x] ruby/ruby@31794d2e73 parse.y: Allow "command" syntax in endless method definition - done in 688359c
- [x] ruby/ruby@d405b1a878 Make imemo_ast WB-protected again
- [x] ruby/ruby@607aa11711 Ignore useless separators preceding a file encoding comment - done in dcfc347
- [x] ruby/ruby@21863470d9 Pattern matching pin operator against expression [Feature #17411] - done in 637b8e9
- [x] ruby/ruby@990b54054d Add a missing semicolon. - nothing to backport
- [x] ruby/ruby@b091889ed6 Removed YYUSE [Bug #17582] - nothing to backport
- [x] ruby/ruby@6bcc4664bd Return new NODE_LIT - nothing to backport
- [x] ruby/ruby@bb40c5cbe9 Ensure symbol list node is either NODE_STR or NODE_DSTR - nothing to backport
- [x] ruby/ruby@0036648a42 Capture to reserved name variables if already defined [Bug #17533] - nothing to backport
- [x] ruby/ruby@7ff0e93f96 parse.y: handle "duplicated argument name" appropriately on ripper.y - ripper, nothing to backport
- [x] ruby/ruby@35c3a24c8c Fixed error message when % at EOF  - done in 8b91170
